name: Node.js CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  setup_dependencies:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-dependencies.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci

  lint:
    needs: setup_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
      - name: Get cached node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ needs.setup_dependencies.outputs.cache-key }}
      - name: Run ESLint
        run: npm run lint

  type-check:
    needs: setup_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
      - name: Get cached node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ needs.setup_dependencies.outputs.cache-key }}
      - name: Run Typescript Compiler
        run: npm run tsc

  test:
    needs: setup_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
      - name: Get cached node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ needs.setup_dependencies.outputs.cache-key }}
      - name: Run Jest tests
        run: npm run test
